name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x64'
    - name: Install system dependencies
      run: |
        sudo apt install -y libhdf4-dev libproj-dev proj-data proj-bin libgeos-dev
    - name: Install the library
      run: |
        pip install setuptools
        pip install -e .
    - name: Run tests
      run: |
        python -m pytest --tb=short -q || true
